animals_list = [
    {
		"animal": "a pig",
		"probability": 1,
		"moo": False,
		"graze": True,
		"have any horns": False,
		"have hooves": True,
		"lay eggs": False,
		"have white colouration": False,
		"eat an omnivorous diet": True,
		"eat a carnivorous diet": False,
		"meow": False,
		"bark": False,
		"cluck": False,
		"peck": False,
		"have feathers": False,
		"fly well": False,
		"oink": True,
		"have a beak": False,
		"have a long mane": False,
		"neigh": False,
		"have wings": False,
		"have wool": False,
		"have a beard": False,
		"have paws": False,
		"quack": False,
		"hee-haw": False,
		"live in a flock": False,
		"live in a herd": False,
		"have a wattle": False,
		"have a comb": False,
        "say gobble": False,
        "give birth to litters": True
    },
    {
		"animal": "a chicken",
		"probability": 1,
		"moo": False,
		"graze": False,
		"have any horns": False,
		"have hooves": False,
		"lay eggs": True,
		"have white colouration": True,
		"eat an omnivorous diet": True,
		"eat a carnivorous diet": False,
		"meow": False,
		"bark": False,
		"cluck": True,
		"peck": True,
		"have feathers": True,
		"fly well": False,
		"oink": False,
		"have a beak": True,
		"have a long mane": False,
		"neigh": False,
		"have wings": True,
		"have wool": False,
		"have a beard": False,
		"have paws": False,
		"quack": False,
		"hee-haw": False,
		"live in a flock": True,
		"live in a herd": False,
		"have a wattle": True,
		"have a comb": True,
        "say gobble": False,
        "give birth to litters": False
	},
    {
		"animal": "a cow",
		"probability": 1,
		"moo": True,
		"graze": True,
		"have any horns": True,
		"have hooves": True,
		"lay eggs": False,
		"have white colouration": True,
		"eat an omnivorous diet": False,
		"eat a carnivorous diet": False,
		"meow": False,
		"bark": False,
		"cluck": False,
		"peck": False,
		"have feathers": False,
		"fly well": False,
		"oink": False,
		"have a beak": False,
		"have a long mane": False,
		"neigh": False,
		"have wings": False,
		"have wool": False,
		"have a beard": False,
		"have paws": False,
		"quack": False,
		"hee-haw": False,
		"live in a flock": False,
		"live in a herd": True,
		"have a wattle": False,
		"have a comb": False,
        "say gobble": False,
        "give birth to litters": False
	},
    {
		"animal": "a horse",
		"probability": 1,
		"moo": False,
		"graze": True,
		"have any horns": False,
		"have hooves": True,
		"lay eggs": False,
		"have white colouration": True,
		"eat an omnivorous diet": False,
		"eat a carnivorous diet": False,
		"meow": False,
		"bark": False,
		"cluck": False,
		"peck": False,
		"have feathers": False,
		"fly well": False,
		"oink": False,
		"have a beak": False,
		"have a long mane": True,
		"neigh": True,
		"have wings": False,
		"have wool": False,
		"have a beard": False,
		"have paws": False,
		"quack": False,
		"hee-haw": False,
		"live in a flock": False,
		"live in a herd": True,
		"have a wattle": False,
		"have a comb": False,
        "say gobble": False,
        "give birth to litters": False
	},
    {
		"animal": "a sheep",
		"probability": 1,
		"moo": False,
		"graze": True,
		"have any horns": True,
		"have hooves": True,
		"lay eggs": False,
		"have white colouration": True,
		"eat an omnivorous diet": False,
		"eat a carnivorous diet": False,
		"meow": False,
		"bark": False,
		"cluck": False,
		"peck": False,
		"have feathers": False,
		"fly well": False,
		"oink": False,
		"have a beak": False,
		"have a long mane": False,
		"neigh": False,
		"have wings": False,
		"have wool": True,
		"have a beard": False,
		"have paws": False,
		"quack": False,
		"hee-haw": False,
		"live in a flock": True,
		"live in a herd": True,
		"have a wattle": False,
		"have a comb": False,
        "say gobble": False,
        "give birth to litters": False
	},
    {
		"animal": "a goat",
		"probability": 1,
		"moo": False,
		"graze": True,
		"have any horns": True,
		"have hooves": True,
		"lay eggs": False,
		"have white colouration": True,
		"eat an omnivorous diet": False,
		"eat a carnivorous diet": False,
		"meow": False,
		"bark": False,
		"cluck": False,
		"peck": False,
		"have feathers": False,
		"fly well": False,
		"oink": False,
		"have a beak": False,
		"have a long mane": False,
		"neigh": False,
		"have wings": False,
		"have wool": False,
		"have a beard": True,
		"have paws": False,
		"quack": False,
		"hee-haw": False,
		"live in a flock": False,
		"live in a herd": True,
		"have a wattle": False,
		"have a comb": False,
        "say gobble": False,
        "give birth to litters": False
	},
    {
		"animal": "a duck",
		"probability": 1,
		"moo": False,
		"graze": False,
		"have any horns": False,
		"have hooves": False,
		"lay eggs": True,
		"have white colouration": True,
		"eat an omnivorous diet": True,
		"eat a carnivorous diet": False,
		"meow": False,
		"bark": False,
		"cluck": False,
		"peck": False,
		"have feathers": True,
		"fly well": True,
		"oink": False,
		"have a beak": True,
		"have a long mane": False,
		"neigh": False,
		"have wings": True,
		"have wool": False,
		"have a beard": False,
		"have paws": False,
		"quack": True,
		"hee-haw": False,
		"live in a flock": True,
		"live in a herd": False,
		"have a wattle": False,
		"have a comb": False,
        "say gobble": False,
        "give birth to litters": False
	}
]